@startuml
abstract class CommonSelectorLogic {
    + CommonSelectorLogic(widget:Widget, world:World, worldRenderer:WorldRenderer, templateListId:string, previewTemplateId:string)
}
ChromeLogic <|-- CommonSelectorLogic
@enduml
