@startuml
class DebugChromeRegions {
    Name : string <<get>>
    ValidateArguments(args:string[]) : bool
    Run(utility:Utility, args:string[]) : void
}
IUtilityCommand <|-- DebugChromeRegions
@enduml
