@startuml
class ExtractSettingsDocsCommand {
    Name : string <<get>>
    ValidateArguments(args:string[]) : bool
    Run(utility:Utility, args:string[]) : void
}
IUtilityCommand <|-- ExtractSettingsDocsCommand
@enduml
