@startuml
class ExtractZeroBraneStudioLuaAPI {
    Name : string <<get>>
    ValidateArguments(args:string[]) : bool
    Run(utility:Utility, args:string[]) : void
}
IUtilityCommand <|-- ExtractZeroBraneStudioLuaAPI
@enduml
