@startuml
class ListInstallShieldContents {
    Name : string <<get>>
    ValidateArguments(args:string[]) : bool
    Run(utility:Utility, args:string[]) : void
}
IUtilityCommand <|-- ListInstallShieldContents
@enduml
