@startuml
class PngSheetImportMetadataCommand {
    Name : string <<get>>
    ValidateArguments(args:string[]) : bool
    Run(utility:Utility, args:string[]) : void
}
IUtilityCommand <|-- PngSheetImportMetadataCommand
@enduml
