@startuml
class PngSheetExportMetadataCommand {
    Name : string <<get>>
    ValidateArguments(args:string[]) : bool
    Run(utility:Utility, args:string[]) : void
}
IUtilityCommand <|-- PngSheetExportMetadataCommand
@enduml
