@startuml
class ReplayMetadataCommand {
    Name : string <<get>>
    ValidateArguments(args:string[]) : bool
    Run(utility:Utility, args:string[]) : void
}
IUtilityCommand <|-- ReplayMetadataCommand
@enduml
