@startuml
class ImportLegacyTilesetCommand {
    Name : string <<get>>
    ValidateArguments(args:string[]) : bool
    Run(utility:Utility, args:string[]) : void
}
IUtilityCommand <|-- ImportLegacyTilesetCommand
@enduml
