@startuml
class ResourcePurifierInfo {
    + <<readonly>> Modifier : int = 0
    + <<readonly>> ShowTicks : bool = true
    + <<readonly>> TickLifetime : int = 30
    + <<readonly>> TickRate : int = 10
    + <<override>> Create(init:ActorInitializer) : object
}
class ResourcePurifier {
    currentDisplayTick : int
    currentDisplayValue : int
    + ResourcePurifier(self:Actor, info:ResourcePurifierInfo)
    OnResourceAccepted(self:Actor, refinery:Actor, amount:int) : void
    Tick(self:Actor) : void
    OnOwnerChanged(self:Actor, oldOwner:Player, newOwner:Player) : void
}
class "ConditionalTrait`1"<T> {
}
ConditionalTraitInfo <|-- ResourcePurifierInfo
"ConditionalTrait`1" "<ResourcePurifierInfo>" <|-- ResourcePurifier
INotifyResourceAccepted <|-- ResourcePurifier
ITick <|-- ResourcePurifier
INotifyOwnerChanged <|-- ResourcePurifier
ResourcePurifier --> "playerResources" PlayerResources
@enduml
