@startuml
class CheckConflictingMouseBounds {
    + Run(emitError:Action<string>, emitWarning:Action<string>, modData:ModData, rules:Ruleset) : void
}
ILintRulesPass <|-- CheckConflictingMouseBounds
@enduml
