@startuml
class CheckDefaultVisibility {
    + Run(emitError:Action<string>, emitWarning:Action<string>, modData:ModData, rules:Ruleset) : void
}
ILintRulesPass <|-- CheckDefaultVisibility
@enduml
