@startuml
class LintBuildablePrerequisites {
    + Run(emitError:Action<string>, emitWarning:Action<string>, modData:ModData, rules:Ruleset) : void
}
ILintRulesPass <|-- LintBuildablePrerequisites
@enduml
