@startuml
class MusicHotkeyLogic {
    + MusicHotkeyLogic(widget:Widget, modData:ModData, world:World, logicArgs:Dictionary<string, MiniYaml>)
    PauseOrResumeMusic() : void
    StopMusic() : void
}
ChromeLogic <|-- MusicHotkeyLogic
MusicHotkeyLogic --> "musicPlaylist" MusicPlaylist
@enduml
