@startuml
class ScreenshotHotkeyLogic {
    + ScreenshotHotkeyLogic(widget:Widget, modData:ModData, logicArgs:Dictionary<string, MiniYaml>)
}
SingleHotkeyBaseLogic <|-- ScreenshotHotkeyLogic
@enduml
