@startuml
class "ProjectedCellLayer`1"<T> <<sealed>> {
    + ProjectedCellLayer(map:Map)
    + ProjectedCellLayer(gridType:MapGridType, size:Size)
    + Index(uv:PPos) : int
    + Contains(uv:PPos) : bool
}
class "CellLayerBase`1"<T> {
}
"CellLayerBase`1" "<T>" <|-- "ProjectedCellLayer`1"
@enduml
