@startuml
class JumpjetActorLayerInfo {
    + <<readonly>> TerrainType : string = "Jumpjet"
    + <<readonly>> SmoothingRadius : int = 2
    + <<override>> Create(init:ActorInitializer) : object
}
class JumpjetActorLayer {
    <<readonly>> terrainIndex : byte
    + JumpjetActorLayer(self:Actor, info:JumpjetActorLayerInfo)
    EnabledForActor(a:ActorInfo, li:LocomotorInfo) : bool
    Index : byte <<get>>
    InteractsWithDefaultLayer : bool <<get>>
    ReturnToGroundLayerOnIdle : bool <<get>>
    CenterOfCell(cell:CPos) : WPos
    ValidTransitionCell(cell:CPos, li:LocomotorInfo) : bool
    EntryMovementCost(a:ActorInfo, li:LocomotorInfo, cell:CPos) : int
    ExitMovementCost(a:ActorInfo, li:LocomotorInfo, cell:CPos) : int
    GetTerrainIndex(cell:CPos) : byte
}
class "CellLayer`1"<T> {
}
TraitInfo <|-- JumpjetActorLayerInfo
JumpjetActorLayerInfo o-> "HeightOffset" WDist
ICustomMovementLayer <|-- JumpjetActorLayer
JumpjetActorLayer --> "map" Map
JumpjetActorLayer --> "height<int>" "CellLayer`1"
@enduml
