@startuml
class ElectricBoltRenderable <<struct>> {
    <<readonly>> zOffset : int
    + ElectricBoltRenderable(offsets:WPos[], zOffset:int, width:WDist, color:Color)
    + ZOffset : int <<get>>
    + IsDecoration : bool <<get>>
    + WithPalette(newPalette:PaletteReference) : IRenderable
    + WithZOffset(newOffset:int) : IRenderable
    + OffsetBy(vec:WVec) : IRenderable
    + AsDecoration() : IRenderable
    + PrepareRender(wr:WorldRenderer) : IFinalizedRenderable
    + Render(wr:WorldRenderer) : void
    + RenderDebugGeometry(wr:WorldRenderer) : void
    + ScreenBounds(wr:WorldRenderer) : Rectangle
}
IRenderable <|-- ElectricBoltRenderable
IFinalizedRenderable <|-- ElectricBoltRenderable
ElectricBoltRenderable --> "width" WDist
ElectricBoltRenderable --> "color" Color
ElectricBoltRenderable --> "Pos" WPos
ElectricBoltRenderable --> "Palette" PaletteReference
@enduml
