@startuml
class ExtendedTilesetSpecificSpriteSequenceLoader {
    + <<readonly>> DefaultSpriteExtension : string = ".shp"
    + ExtendedTilesetSpecificSpriteSequenceLoader(modData:ModData)
    + <<override>> CreateSequence(modData:ModData, tileSet:string, cache:SpriteCache, sequence:string, animation:string, info:MiniYaml) : ISpriteSequence
}
class ExtendedTilesetSpecificSpriteSequence {
    + ExtendedTilesetSpecificSpriteSequence(modData:ModData, tileSet:string, cache:SpriteCache, loader:ISpriteSequenceLoader, sequence:string, animation:string, info:MiniYaml)
    ResolveTilesetId(tileSet:string, d:Dictionary<string, MiniYaml>) : string
}
class "Dictionary`2"<T1,T2> {
}
DefaultSpriteSequenceLoader <|-- ExtendedTilesetSpecificSpriteSequenceLoader
ExtendedTilesetSpecificSpriteSequenceLoader o-> "TilesetExtensions<string,string>" "Dictionary`2"
ExtendedTilesetSpecificSpriteSequenceLoader o-> "TilesetCodes<string,string>" "Dictionary`2"
ExtendedTilesetSpecificSpriteSequenceLoader o-> "TilesetSuffixes<string,string>" "Dictionary`2"
DefaultSpriteSequence <|-- ExtendedTilesetSpecificSpriteSequence
@enduml
