@startuml
class CycleStatusBarsHotkeyLogic {
    + CycleStatusBarsHotkeyLogic(widget:Widget, modData:ModData, logicArgs:Dictionary<string, MiniYaml>)
}
SingleHotkeyBaseLogic <|-- CycleStatusBarsHotkeyLogic
@enduml
