@startuml
class JumpToSelectedActorsHotkeyLogic {
    + JumpToSelectedActorsHotkeyLogic(widget:Widget, modData:ModData, worldRenderer:WorldRenderer, world:World, logicArgs:Dictionary<string, MiniYaml>)
}
SingleHotkeyBaseLogic <|-- JumpToSelectedActorsHotkeyLogic
JumpToSelectedActorsHotkeyLogic --> "viewport" Viewport
JumpToSelectedActorsHotkeyLogic --> "selection" ISelection
@enduml
