@startuml
class GrantConditionOnPowerStateInfo {
    + <<readonly>> Condition : string = null
    + <<override>> Create(init:ActorInitializer) : object
}
class GrantConditionOnPowerState {
    conditionToken : int
    validPowerState : bool
    + GrantConditionOnPowerState(self:Actor, info:GrantConditionOnPowerStateInfo)
    Update(self:Actor) : void
    PowerLevelChanged(self:Actor) : void
    OnOwnerChanged(self:Actor, oldOwner:Player, newOwner:Player) : void
}
class "ConditionalTrait`1"<T> {
}
ConditionalTraitInfo <|-- GrantConditionOnPowerStateInfo
GrantConditionOnPowerStateInfo o-> "ValidPowerStates" PowerState
"ConditionalTrait`1" "<GrantConditionOnPowerStateInfo>" <|-- GrantConditionOnPowerState
INotifyOwnerChanged <|-- GrantConditionOnPowerState
INotifyPowerLevelChanged <|-- GrantConditionOnPowerState
GrantConditionOnPowerState --> "playerPower" PowerManager
@enduml
