@startuml
class GrantConditionOnPrerequisiteInfo {
    + <<readonly>> Condition : string = null
    + <<override>> Create(init:ActorInitializer) : object
}
class GrantConditionOnPrerequisite {
    wasAvailable : bool
    conditionToken : int
    + GrantConditionOnPrerequisite(self:Actor, info:GrantConditionOnPrerequisiteInfo)
    Created(self:Actor) : void
    AddedToWorld(self:Actor) : void
    RemovedFromWorld(self:Actor) : void
    OnOwnerChanged(self:Actor, oldOwner:Player, newOwner:Player) : void
    + PrerequisitesUpdated(self:Actor, available:bool) : void
}
TraitInfo <|-- GrantConditionOnPrerequisiteInfo
INotifyCreated <|-- GrantConditionOnPrerequisite
INotifyAddedToWorld <|-- GrantConditionOnPrerequisite
INotifyRemovedFromWorld <|-- GrantConditionOnPrerequisite
INotifyOwnerChanged <|-- GrantConditionOnPrerequisite
GrantConditionOnPrerequisite --> "info" GrantConditionOnPrerequisiteInfo
GrantConditionOnPrerequisite --> "globalManager" GrantConditionOnPrerequisiteManager
@enduml
