@startuml
class ClearInvalidModRegistrationsCommand {
    Name : string <<get>>
    ValidateArguments(args:string[]) : bool
    Run(utility:Utility, args:string[]) : void
}
IUtilityCommand <|-- ClearInvalidModRegistrationsCommand
@enduml
