@startuml
class LobbySettingsNotification {
    + ClientJoined(server:OpenRA.Server.Server, conn:Connection) : void
}
ServerTrait <|-- LobbySettingsNotification
IClientJoined <|-- LobbySettingsNotification
@enduml
