@startuml
class ProvidesTechPrerequisiteInfo {
    + <<readonly>> Id : string
    + <<readonly>> Name : string
    Prerequisites(info:ActorInfo) : IEnumerable<string>
    + <<override>> Create(init:ActorInitializer) : object
}
class ProvidesTechPrerequisite {
    enabled : bool
    + Name : string <<get>>
    + ProvidesTechPrerequisite(info:ProvidesTechPrerequisiteInfo, init:ActorInitializer)
}
class "IEnumerable`1"<T> {
}
TraitInfo <|-- ProvidesTechPrerequisiteInfo
ITechTreePrerequisiteInfo <|-- ProvidesTechPrerequisiteInfo
ITechTreePrerequisite <|-- ProvidesTechPrerequisite
ProvidesTechPrerequisite --> "info" ProvidesTechPrerequisiteInfo
ProvidesTechPrerequisite --> "ProvidesPrerequisites<string>" "IEnumerable`1"
@enduml
