@startuml
class ProvidesPrerequisiteInfo {
    + <<readonly>> Prerequisite : string = null
    + <<readonly>> ResetOnOwnerChange : bool = false
    Prerequisites(info:ActorInfo) : IEnumerable<string>
    + <<override>> Create(init:ActorInitializer) : object
}
class ProvidesPrerequisite {
    <<readonly>> prerequisite : string
    enabled : bool
    faction : string
    + ProvidesPrerequisite(init:ActorInitializer, info:ProvidesPrerequisiteInfo)
    + OnOwnerChanged(self:Actor, oldOwner:Player, newOwner:Player) : void
    Update() : void
}
class "HashSet`1"<T> {
}
class "ConditionalTrait`1"<T> {
}
class "IEnumerable`1"<T> {
}
ConditionalTraitInfo <|-- ProvidesPrerequisiteInfo
ITechTreePrerequisiteInfo <|-- ProvidesPrerequisiteInfo
ProvidesPrerequisiteInfo o-> "Factions<string>" "HashSet`1"
"ConditionalTrait`1" "<ProvidesPrerequisiteInfo>" <|-- ProvidesPrerequisite
ITechTreePrerequisite <|-- ProvidesPrerequisite
INotifyOwnerChanged <|-- ProvidesPrerequisite
INotifyCreated <|-- ProvidesPrerequisite
ProvidesPrerequisite --> "techTree" TechTree
ProvidesPrerequisite --> "ProvidesPrerequisites<string>" "IEnumerable`1"
@enduml
