@startuml
class RemoveWithPermanentInjury {
    + <<override>> Name : string <<get>>
    + <<override>> Description : string <<get>>
    + <<override>> AfterUpdate(modData:ModData) : IEnumerable<string>
    + <<override>> UpdateActorNode(modData:ModData, actorNode:MiniYamlNode) : IEnumerable<string>
}
class "List`1"<T> {
}
UpdateRule <|-- RemoveWithPermanentInjury
RemoveWithPermanentInjury o-> "locations<string>" "List`1"
@enduml
