@startuml
class ReplaceAttackTypeStrafe {
    + <<override>> Name : string <<get>>
    + <<override>> Description : string <<get>>
    + <<override>> UpdateActorNode(modData:ModData, actorNode:MiniYamlNode) : IEnumerable<string>
}
UpdateRule <|-- ReplaceAttackTypeStrafe
@enduml
