@startuml
class LatencyTooltipLogic {
    + LatencyTooltipLogic(widget:Widget, tooltipContainer:TooltipContainerWidget, orderManager:OrderManager, client:Session.Client)
}
ChromeLogic <|-- LatencyTooltipLogic
@enduml
