@startuml
class GradientColorBlockWidget {
    + GradientColorBlockWidget()
    + <<override>> Clone() : Widget
    + <<override>> Draw() : void
}
class "Func`1"<T> {
}
Widget <|-- GradientColorBlockWidget
GradientColorBlockWidget --> "TopLeftColor" Color
GradientColorBlockWidget --> "TopRightColor" Color
GradientColorBlockWidget --> "BottomRightColor" Color
GradientColorBlockWidget --> "BottomLeftColor" Color
GradientColorBlockWidget --> "GetTopLeftColor<Color>" "Func`1"
GradientColorBlockWidget --> "GetTopRightColor<Color>" "Func`1"
GradientColorBlockWidget --> "GetBottomRightColor<Color>" "Func`1"
GradientColorBlockWidget --> "GetBottomLeftColor<Color>" "Func`1"
@enduml
