@startuml
class ProductionTypeButtonWidget {
    + <<readonly>> ProductionGroup : string
    + ProductionTypeButtonWidget(modData:ModData, world:World)
}
WorldButtonWidget <|-- ProductionTypeButtonWidget
@enduml
