@startuml
page 10x10
!include .\\engine\OpenRA.Game\Actor.puml
!include .\\engine\OpenRA.Game\CacheStorage.puml
!include .\\engine\OpenRA.Game\CPos.puml
!include .\\engine\OpenRA.Game\CryptoUtil.puml
!include .\\engine\OpenRA.Game\CVec.puml
!include .\\engine\OpenRA.Game\DefaultPlayer.puml
!include .\\engine\OpenRA.Game\Download.puml
!include .\\engine\OpenRA.Game\ExternalMods.puml
!include .\\engine\OpenRA.Game\Exts.puml
!include .\\engine\OpenRA.Game\FieldLoader.puml
!include .\\engine\OpenRA.Game\FieldSaver.puml
!include .\\engine\OpenRA.Game\Fonts.puml
!include .\\engine\OpenRA.Game\Game.puml
!include .\\engine\OpenRA.Game\GameInformation.puml
!include .\\engine\OpenRA.Game\GameSpeed.puml
!include .\\engine\OpenRA.Game\HotkeyDefinition.puml
!include .\\engine\OpenRA.Game\HotkeyManager.puml
!include .\\engine\OpenRA.Game\InstalledMods.puml
!include .\\engine\OpenRA.Game\IUtilityCommand.puml
!include .\\engine\OpenRA.Game\LocalPlayerProfile.puml
!include .\\engine\OpenRA.Game\LogProxy.puml
!include .\\engine\OpenRA.Game\Manifest.puml
!include .\\engine\OpenRA.Game\MiniYaml.puml
!include .\\engine\OpenRA.Game\ModData.puml
!include .\\engine\OpenRA.Game\MPos.puml
!include .\\engine\OpenRA.Game\ObjectCreator.puml
!include .\\engine\OpenRA.Game\Platform.puml
!include .\\engine\OpenRA.Game\Player.puml
!include .\\engine\OpenRA.Game\PlayerDatabase.puml
!include .\\engine\OpenRA.Game\PlayerProfile.puml
!include .\\engine\OpenRA.Game\Renderer.puml
!include .\\engine\OpenRA.Game\SelectableExts.puml
!include .\\engine\OpenRA.Game\Settings.puml
!include .\\engine\OpenRA.Game\StreamExts.puml
!include .\\engine\OpenRA.Game\Sync.puml
!include .\\engine\OpenRA.Game\TraitDictionary.puml
!include .\\engine\OpenRA.Game\VoiceExts.puml
!include .\\engine\OpenRA.Game\WAngle.puml
!include .\\engine\OpenRA.Game\WDist.puml
!include .\\engine\OpenRA.Game\World.puml
!include .\\engine\OpenRA.Game\WorldUtils.puml
!include .\\engine\OpenRA.Game\WorldViewportSizes.puml
!include .\\engine\OpenRA.Game\WPos.puml
!include .\\engine\OpenRA.Game\WRot.puml
!include .\\engine\OpenRA.Game\WVec.puml
!include .\\engine\OpenRA.Launcher\Program.puml
!include .\\engine\OpenRA.Mods.Cnc\CncLoadScreen.puml
!include .\\engine\OpenRA.Mods.Cnc\TraitsInterfaces.puml
!include .\\engine\OpenRA.Mods.Cnc\Util.puml
!include .\\engine\OpenRA.Mods.Common\ActorExts.puml
!include .\\engine\OpenRA.Mods.Common\ActorInitializer.puml
!include .\\engine\OpenRA.Mods.Common\AIUtils.puml
!include .\\engine\OpenRA.Mods.Common\AssetBrowser.puml
!include .\\engine\OpenRA.Mods.Common\ColorValidator.puml
!include .\\engine\OpenRA.Mods.Common\DiscordService.puml
!include .\\engine\OpenRA.Mods.Common\ModContent.puml
!include .\\engine\OpenRA.Mods.Common\ModCredits.puml
!include .\\engine\OpenRA.Mods.Common\PlayerExtensions.puml
!include .\\engine\OpenRA.Mods.Common\ShroudExts.puml
!include .\\engine\OpenRA.Mods.Common\TargetExtensions.puml
!include .\\engine\OpenRA.Mods.Common\TraitsInterfaces.puml
!include .\\engine\OpenRA.Mods.Common\Util.puml
!include .\\engine\OpenRA.Mods.Common\WebServices.puml
!include .\\engine\OpenRA.Mods.Common\WorldExtensions.puml
!include .\\engine\OpenRA.Platforms.Default\DefaultPlatform.puml
!include .\\engine\OpenRA.Platforms.Default\DummySoundEngine.puml
!include .\\engine\OpenRA.Platforms.Default\FrameBuffer.puml
!include .\\engine\OpenRA.Platforms.Default\FreeTypeFont.puml
!include .\\engine\OpenRA.Platforms.Default\ITextureInternal.puml
!include .\\engine\OpenRA.Platforms.Default\MultiTapDetection.puml
!include .\\engine\OpenRA.Platforms.Default\OpenAlSoundEngine.puml
!include .\\engine\OpenRA.Platforms.Default\OpenGL.puml
!include .\\engine\OpenRA.Platforms.Default\Sdl2GraphicsContext.puml
!include .\\engine\OpenRA.Platforms.Default\Sdl2HardwareCursor.puml
!include .\\engine\OpenRA.Platforms.Default\Sdl2Input.puml
!include .\\engine\OpenRA.Platforms.Default\Sdl2PlatformWindow.puml
!include .\\engine\OpenRA.Platforms.Default\Shader.puml
!include .\\engine\OpenRA.Platforms.Default\Texture.puml
!include .\\engine\OpenRA.Platforms.Default\ThreadAffine.puml
!include .\\engine\OpenRA.Platforms.Default\ThreadedGraphicsContext.puml
!include .\\engine\OpenRA.Platforms.Default\VertexBuffer.puml
!include .\\engine\OpenRA.Server\Program.puml
!include .\\engine\OpenRA.Utility\Program.puml
!include .\\engine\OpenRA.WindowsLauncher\Program.puml
!include .\\OpenRA.Mods.RA2\Activities\ChronoResourceTeleport.puml
!include .\\OpenRA.Mods.RA2\Activities\EnterCarrierParent.puml
!include .\\OpenRA.Mods.RA2\FileSystem\BagFile.puml
!include .\\OpenRA.Mods.RA2\Graphics\ArcRenderable.puml
!include .\\OpenRA.Mods.RA2\Graphics\ElectricBoltRenderable.puml
!include .\\OpenRA.Mods.RA2\Graphics\ExtendedTilesetSpecificSpriteSequenceLoader.puml
!include .\\OpenRA.Mods.RA2\Graphics\RadBeamRenderable.puml
!include .\\OpenRA.Mods.RA2\Graphics\TintedCell.puml
!include .\\OpenRA.Mods.RA2\Projectiles\ArcLaserZap.puml
!include .\\OpenRA.Mods.RA2\Projectiles\ElectricBolt.puml
!include .\\OpenRA.Mods.RA2\Projectiles\RadBeam.puml
!include .\\OpenRA.Mods.RA2\Traits\BaseSpawnerChild.puml
!include .\\OpenRA.Mods.RA2\Traits\BaseSpawnerParent.puml
!include .\\OpenRA.Mods.RA2\Traits\CarrierChild.puml
!include .\\OpenRA.Mods.RA2\Traits\CarrierParent.puml
!include .\\OpenRA.Mods.RA2\Traits\ChronoResourceDelivery.puml
!include .\\OpenRA.Mods.RA2\Traits\ChronoshiftableWithSpriteEffect.puml
!include .\\OpenRA.Mods.RA2\Traits\DamagedByTintedCells.puml
!include .\\OpenRA.Mods.RA2\Traits\MindControllable.puml
!include .\\OpenRA.Mods.RA2\Traits\MindController.puml
!include .\\OpenRA.Mods.RA2\Traits\Mirage.puml
!include .\\OpenRA.Mods.RA2\Traits\PeriodicExplosion.puml
!include .\\OpenRA.Mods.RA2\Traits\SpawnSurvivors.puml
!include .\\OpenRA.Mods.RA2\Traits\WeatherControlSupportPower.puml
!include .\\OpenRA.Mods.RA2\Traits\WeatherPaletteEffect.puml
!include .\\OpenRA.Mods.RA2\Warheads\CreateTintedCellsWarhead.puml
!include .\\OpenRA.Mods.RA2\Widgets\PowerMeterWidget.puml
!include .\\engine\OpenRA.Game\Activities\Activity.puml
!include .\\engine\OpenRA.Game\Activities\CallFunc.puml
!include .\\engine\OpenRA.Game\Effects\AsyncAction.puml
!include .\\engine\OpenRA.Game\Effects\DelayedAction.puml
!include .\\engine\OpenRA.Game\Effects\DelayedImpact.puml
!include .\\engine\OpenRA.Game\Effects\IEffect.puml
!include .\\engine\OpenRA.Game\FileFormats\Png.puml
!include .\\engine\OpenRA.Game\FileFormats\ReplayMetadata.puml
!include .\\engine\OpenRA.Game\FileSystem\FileSystem.puml
!include .\\engine\OpenRA.Game\FileSystem\Folder.puml
!include .\\engine\OpenRA.Game\FileSystem\IPackage.puml
!include .\\engine\OpenRA.Game\FileSystem\ZipFile.puml
!include .\\engine\OpenRA.Game\GameRules\ActorInfo.puml
!include .\\engine\OpenRA.Game\GameRules\MusicInfo.puml
!include .\\engine\OpenRA.Game\GameRules\Ruleset.puml
!include .\\engine\OpenRA.Game\GameRules\SoundInfo.puml
!include .\\engine\OpenRA.Game\GameRules\WeaponInfo.puml
!include .\\engine\OpenRA.Game\Graphics\Animation.puml
!include .\\engine\OpenRA.Game\Graphics\AnimationWithOffset.puml
!include .\\engine\OpenRA.Game\Graphics\ChromeProvider.puml
!include .\\engine\OpenRA.Game\Graphics\CursorManager.puml
!include .\\engine\OpenRA.Game\Graphics\CursorProvider.puml
!include .\\engine\OpenRA.Game\Graphics\CursorSequence.puml
!include .\\engine\OpenRA.Game\Graphics\HardwarePalette.puml
!include .\\engine\OpenRA.Game\Graphics\Model.puml
!include .\\engine\OpenRA.Game\Graphics\ModelAnimation.puml
!include .\\engine\OpenRA.Game\Graphics\ModelRenderer.puml
!include .\\engine\OpenRA.Game\Graphics\Palette.puml
!include .\\engine\OpenRA.Game\Graphics\PaletteReference.puml
!include .\\engine\OpenRA.Game\Graphics\PlatformInterfaces.puml
!include .\\engine\OpenRA.Game\Graphics\PlayerColorRemap.puml
!include .\\engine\OpenRA.Game\Graphics\Renderable.puml
!include .\\engine\OpenRA.Game\Graphics\RgbaColorRenderer.puml
!include .\\engine\OpenRA.Game\Graphics\RgbaSpriteRenderer.puml
!include .\\engine\OpenRA.Game\Graphics\SequenceProvider.puml
!include .\\engine\OpenRA.Game\Graphics\Sheet.puml
!include .\\engine\OpenRA.Game\Graphics\SheetBuilder.puml
!include .\\engine\OpenRA.Game\Graphics\Sprite.puml
!include .\\engine\OpenRA.Game\Graphics\SpriteFont.puml
!include .\\engine\OpenRA.Game\Graphics\SpriteLoader.puml
!include .\\engine\OpenRA.Game\Graphics\SpriteRenderable.puml
!include .\\engine\OpenRA.Game\Graphics\SpriteRenderer.puml
!include .\\engine\OpenRA.Game\Graphics\TargetLineRenderable.puml
!include .\\engine\OpenRA.Game\Graphics\TerrainSpriteLayer.puml
!include .\\engine\OpenRA.Game\Graphics\Theater.puml
!include .\\engine\OpenRA.Game\Graphics\UISpriteRenderable.puml
!include .\\engine\OpenRA.Game\Graphics\Util.puml
!include .\\engine\OpenRA.Game\Graphics\Vertex.puml
!include .\\engine\OpenRA.Game\Graphics\Viewport.puml
!include .\\engine\OpenRA.Game\Graphics\WorldRenderer.puml
!include .\\engine\OpenRA.Game\Input\Hotkey.puml
!include .\\engine\OpenRA.Game\Input\HotkeyReference.puml
!include .\\engine\OpenRA.Game\Input\IInputHandler.puml
!include .\\engine\OpenRA.Game\Input\InputHandler.puml
!include .\\engine\OpenRA.Game\Input\Keycode.puml
!include .\\engine\OpenRA.Game\Map\ActorInitializer.puml
!include .\\engine\OpenRA.Game\Map\ActorReference.puml
!include .\\engine\OpenRA.Game\Map\CellLayer.puml
!include .\\engine\OpenRA.Game\Map\CellLayerBase.puml
!include .\\engine\OpenRA.Game\Map\CellRegion.puml
!include .\\engine\OpenRA.Game\Map\Map.puml
!include .\\engine\OpenRA.Game\Map\MapCache.puml
!include .\\engine\OpenRA.Game\Map\MapCoordsRegion.puml
!include .\\engine\OpenRA.Game\Map\MapGrid.puml
!include .\\engine\OpenRA.Game\Map\MapPlayers.puml
!include .\\engine\OpenRA.Game\Map\MapPreview.puml
!include .\\engine\OpenRA.Game\Map\PlayerReference.puml
!include .\\engine\OpenRA.Game\Map\ProjectedCellLayer.puml
!include .\\engine\OpenRA.Game\Map\ProjectedCellRegion.puml
!include .\\engine\OpenRA.Game\Map\TileReference.puml
!include .\\engine\OpenRA.Game\Map\TileSet.puml
!include .\\engine\OpenRA.Game\Network\Connection.puml
!include .\\engine\OpenRA.Game\Network\FrameData.puml
!include .\\engine\OpenRA.Game\Network\GameSave.puml
!include .\\engine\OpenRA.Game\Network\GameServer.puml
!include .\\engine\OpenRA.Game\Network\GeoIP.puml
!include .\\engine\OpenRA.Game\Network\Handshake.puml
!include .\\engine\OpenRA.Game\Network\Order.puml
!include .\\engine\OpenRA.Game\Network\OrderIO.puml
!include .\\engine\OpenRA.Game\Network\OrderManager.puml
!include .\\engine\OpenRA.Game\Network\ReplayConnection.puml
!include .\\engine\OpenRA.Game\Network\ReplayRecorder.puml
!include .\\engine\OpenRA.Game\Network\Session.puml
!include .\\engine\OpenRA.Game\Network\SyncReport.puml
!include .\\engine\OpenRA.Game\Network\UnitOrders.puml
!include .\\engine\OpenRA.Game\Network\UPnP.puml
!include .\\engine\OpenRA.Game\Orders\GenericSelectTarget.puml
!include .\\engine\OpenRA.Game\Orders\IOrderGenerator.puml
!include .\\engine\OpenRA.Game\Orders\UnitOrderGenerator.puml
!include .\\engine\OpenRA.Game\Primitives\ActionQueue.puml
!include .\\engine\OpenRA.Game\Primitives\BitSet.puml
!include .\\engine\OpenRA.Game\Primitives\Cache.puml
!include .\\engine\OpenRA.Game\Primitives\Color.puml
!include .\\engine\OpenRA.Game\Primitives\ConcurrentCache.puml
!include .\\engine\OpenRA.Game\Primitives\DisposableAction.puml
!include .\\engine\OpenRA.Game\Primitives\float2.puml
!include .\\engine\OpenRA.Game\Primitives\float3.puml
!include .\\engine\OpenRA.Game\Primitives\int2.puml
!include .\\engine\OpenRA.Game\Primitives\Int32Matrix4x4.puml
!include .\\engine\OpenRA.Game\Primitives\IObservableCollection.puml
!include .\\engine\OpenRA.Game\Primitives\LongBitSet.puml
!include .\\engine\OpenRA.Game\Primitives\MergedStream.puml
!include .\\engine\OpenRA.Game\Primitives\ObservableCollection.puml
!include .\\engine\OpenRA.Game\Primitives\ObservableDictionary.puml
!include .\\engine\OpenRA.Game\Primitives\ObservableList.puml
!include .\\engine\OpenRA.Game\Primitives\PlayerDictionary.puml
!include .\\engine\OpenRA.Game\Primitives\Polygon.puml
!include .\\engine\OpenRA.Game\Primitives\PriorityQueue.puml
!include .\\engine\OpenRA.Game\Primitives\ReadOnlyAdapterStream.puml
!include .\\engine\OpenRA.Game\Primitives\ReadOnlyDictionary.puml
!include .\\engine\OpenRA.Game\Primitives\ReadOnlyList.puml
!include .\\engine\OpenRA.Game\Primitives\Rectangle.puml
!include .\\engine\OpenRA.Game\Primitives\SegmentStream.puml
!include .\\engine\OpenRA.Game\Primitives\Size.puml
!include .\\engine\OpenRA.Game\Primitives\SpatiallyPartitioned.puml
!include .\\engine\OpenRA.Game\Primitives\TypeDictionary.puml
!include .\\engine\OpenRA.Game\Scripting\ScriptActorInterface.puml
!include .\\engine\OpenRA.Game\Scripting\ScriptContext.puml
!include .\\engine\OpenRA.Game\Scripting\ScriptMemberExts.puml
!include .\\engine\OpenRA.Game\Scripting\ScriptMemberWrapper.puml
!include .\\engine\OpenRA.Game\Scripting\ScriptObjectWrapper.puml
!include .\\engine\OpenRA.Game\Scripting\ScriptPlayerInterface.puml
!include .\\engine\OpenRA.Game\Scripting\ScriptTypes.puml
!include .\\engine\OpenRA.Game\Server\Connection.puml
!include .\\engine\OpenRA.Game\Server\Exts.puml
!include .\\engine\OpenRA.Game\Server\ProtocolVersion.puml
!include .\\engine\OpenRA.Game\Server\Server.puml
!include .\\engine\OpenRA.Game\Server\TraitInterfaces.puml
!include .\\engine\OpenRA.Game\Sound\Sound.puml
!include .\\engine\OpenRA.Game\Sound\SoundDevice.puml
!include .\\engine\OpenRA.Game\Support\Arguments.puml
!include .\\engine\OpenRA.Game\Support\Benchmark.puml
!include .\\engine\OpenRA.Game\Support\Evaluator.puml
!include .\\engine\OpenRA.Game\Support\ExceptionHandler.puml
!include .\\engine\OpenRA.Game\Support\LaunchArguments.puml
!include .\\engine\OpenRA.Game\Support\Log.puml
!include .\\engine\OpenRA.Game\Support\MersenneTwister.puml
!include .\\engine\OpenRA.Game\Support\PerfHistory.puml
!include .\\engine\OpenRA.Game\Support\PerfItem.puml
!include .\\engine\OpenRA.Game\Support\PerfSample.puml
!include .\\engine\OpenRA.Game\Support\PerfTimer.puml
!include .\\engine\OpenRA.Game\Support\Program.puml
!include .\\engine\OpenRA.Game\Support\VariableExpression.puml
!include .\\engine\OpenRA.Game\Traits\ActivityUtils.puml
!include .\\engine\OpenRA.Game\Traits\DebugPauseState.puml
!include .\\engine\OpenRA.Game\Traits\LintAttributes.puml
!include .\\engine\OpenRA.Game\Traits\Target.puml
!include .\\engine\OpenRA.Game\Traits\TraitsInterfaces.puml
!include .\\engine\OpenRA.Game\UtilityCommands\ClearInvalidModRegistrationsCommand.puml
!include .\\engine\OpenRA.Game\UtilityCommands\RegisterModCommand.puml
!include .\\engine\OpenRA.Game\UtilityCommands\UnregisterModCommand.puml
!include .\\engine\OpenRA.Game\Widgets\ChromeMetrics.puml
!include .\\engine\OpenRA.Game\Widgets\Widget.puml
!include .\\engine\OpenRA.Game\Widgets\WidgetLoader.puml
!include .\\engine\OpenRA.Mods.Cnc\Activities\Infiltrate.puml
!include .\\engine\OpenRA.Mods.Cnc\Activities\LayMines.puml
!include .\\engine\OpenRA.Mods.Cnc\Activities\Leap.puml
!include .\\engine\OpenRA.Mods.Cnc\Activities\LeapAttack.puml
!include .\\engine\OpenRA.Mods.Cnc\Activities\Teleport.puml
!include .\\engine\OpenRA.Mods.Cnc\Activities\VoxelHarvesterDockSequence.puml
!include .\\engine\OpenRA.Mods.Cnc\AudioLoaders\AudLoader.puml
!include .\\engine\OpenRA.Mods.Cnc\AudioLoaders\VocLoader.puml
!include .\\engine\OpenRA.Mods.Cnc\Effects\GpsDotEffect.puml
!include .\\engine\OpenRA.Mods.Cnc\Effects\GpsSatellite.puml
!include .\\engine\OpenRA.Mods.Cnc\Effects\SatelliteLaunch.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\AudReader.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\Blowfish.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\BlowfishKeyProvider.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\CRC32.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\HvaReader.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\IdxEntry.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\IdxReader.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\LCWCompression.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\LZOCompression.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\VxlReader.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\XccGlobalDatabase.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\XccLocalDatabase.puml
!include .\\engine\OpenRA.Mods.Cnc\FileFormats\XORDeltaCompression.puml
!include .\\engine\OpenRA.Mods.Cnc\FileSystem\BigFile.puml
!include .\\engine\OpenRA.Mods.Cnc\FileSystem\MixFile.puml
!include .\\engine\OpenRA.Mods.Cnc\FileSystem\PackageEntry.puml
!include .\\engine\OpenRA.Mods.Cnc\FileSystem\Pak.puml
!include .\\engine\OpenRA.Mods.Cnc\Graphics\ClassicSpriteSequence.puml
!include .\\engine\OpenRA.Mods.Cnc\Graphics\ClassicTilesetSpecificSpriteSequence.puml
!include .\\engine\OpenRA.Mods.Cnc\Graphics\TeslaZapRenderable.puml
!include .\\engine\OpenRA.Mods.Cnc\Graphics\Voxel.puml
!include .\\engine\OpenRA.Mods.Cnc\Graphics\VoxelLoader.puml
!include .\\engine\OpenRA.Mods.Cnc\Graphics\VoxelModelSequenceLoader.puml
!include .\\engine\OpenRA.Mods.Cnc\Projectiles\DropPodImpact.puml
!include .\\engine\OpenRA.Mods.Cnc\Projectiles\IonCannon.puml
!include .\\engine\OpenRA.Mods.Cnc\Projectiles\TeslaZap.puml
!include .\\engine\OpenRA.Mods.Cnc\SpriteLoaders\ShpD2Loader.puml
!include .\\engine\OpenRA.Mods.Cnc\SpriteLoaders\ShpTDLoader.puml
!include .\\engine\OpenRA.Mods.Cnc\SpriteLoaders\TmpRALoader.puml
!include .\\engine\OpenRA.Mods.Cnc\SpriteLoaders\TmpTDLoader.puml
!include .\\engine\OpenRA.Mods.Cnc\SpriteLoaders\TmpTSLoader.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Chronoshiftable.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\ClassicFacingBodyOrientation.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Cloneable.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\ConyardChronoReturn.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Disguise.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\DrainPrerequisitePowerOnDamage.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\EdibleByLeap.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\EnergyWall.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\FrozenUnderFogUpdatedByGps.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\GpsDot.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\GpsWatcher.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\HarvesterHuskModifier.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\MadTank.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Mine.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Minelayer.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\PortableChrono.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\ResourcePurifier.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\TDGunboat.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\TransferTimedExternalConditionOnTransform.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\TransformsNearResources.puml
!include .\\engine\OpenRA.Mods.Cnc\UtilityCommands\ConvertPngToShpCommand.puml
!include .\\engine\OpenRA.Mods.Cnc\UtilityCommands\Glob.puml
!include .\\engine\OpenRA.Mods.Cnc\UtilityCommands\ImportRedAlertLegacyMapCommand.puml
!include .\\engine\OpenRA.Mods.Cnc\UtilityCommands\ImportTiberianDawnLegacyMapCommand.puml
!include .\\engine\OpenRA.Mods.Cnc\UtilityCommands\ImportTSMapCommand.puml
!include .\\engine\OpenRA.Mods.Cnc\UtilityCommands\LegacyRulesImporter.puml
!include .\\engine\OpenRA.Mods.Cnc\UtilityCommands\LegacySequenceImporter.puml
!include .\\engine\OpenRA.Mods.Cnc\UtilityCommands\LegacyTilesetImporter.puml
!include .\\engine\OpenRA.Mods.Cnc\UtilityCommands\ListMixContentsCommand.puml
!include .\\engine\OpenRA.Mods.Cnc\UtilityCommands\RemapShpCommand.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Attack.puml
!include .\\engine\OpenRA.Mods.Common\Activities\CaptureActor.puml
!include .\\engine\OpenRA.Mods.Common\Activities\DeliverResources.puml
!include .\\engine\OpenRA.Mods.Common\Activities\DeliverUnit.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Demolish.puml
!include .\\engine\OpenRA.Mods.Common\Activities\DeployForGrantedCondition.puml
!include .\\engine\OpenRA.Mods.Common\Activities\DonateCash.puml
!include .\\engine\OpenRA.Mods.Common\Activities\DonateExperience.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Enter.puml
!include .\\engine\OpenRA.Mods.Common\Activities\FindAndDeliverResources.puml
!include .\\engine\OpenRA.Mods.Common\Activities\HarvesterDockSequence.puml
!include .\\engine\OpenRA.Mods.Common\Activities\HarvestResource.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Hunt.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Parachute.puml
!include .\\engine\OpenRA.Mods.Common\Activities\PickupUnit.puml
!include .\\engine\OpenRA.Mods.Common\Activities\RemoveSelf.puml
!include .\\engine\OpenRA.Mods.Common\Activities\RepairBridge.puml
!include .\\engine\OpenRA.Mods.Common\Activities\RepairBuilding.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Resupply.puml
!include .\\engine\OpenRA.Mods.Common\Activities\RideTransport.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Sell.puml
!include .\\engine\OpenRA.Mods.Common\Activities\SimpleTeleport.puml
!include .\\engine\OpenRA.Mods.Common\Activities\SpriteHarvesterDockSequence.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Transform.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Turn.puml
!include .\\engine\OpenRA.Mods.Common\Activities\UnloadCargo.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Wait.puml
!include .\\engine\OpenRA.Mods.Common\AudioLoaders\WavLoader.puml
!include .\\engine\OpenRA.Mods.Common\Commands\ChatCommands.puml
!include .\\engine\OpenRA.Mods.Common\Commands\DebugVisualizationCommands.puml
!include .\\engine\OpenRA.Mods.Common\Commands\DevCommands.puml
!include .\\engine\OpenRA.Mods.Common\Commands\HelpCommand.puml
!include .\\engine\OpenRA.Mods.Common\Commands\PlayerCommands.puml
!include .\\engine\OpenRA.Mods.Common\EditorBrushes\EditorActorBrush.puml
!include .\\engine\OpenRA.Mods.Common\EditorBrushes\EditorCopyPasteBrush.puml
!include .\\engine\OpenRA.Mods.Common\EditorBrushes\EditorDefaultBrush.puml
!include .\\engine\OpenRA.Mods.Common\EditorBrushes\EditorResourceBrush.puml
!include .\\engine\OpenRA.Mods.Common\EditorBrushes\EditorTileBrush.puml
!include .\\engine\OpenRA.Mods.Common\Effects\Beacon.puml
!include .\\engine\OpenRA.Mods.Common\Effects\ContrailFader.puml
!include .\\engine\OpenRA.Mods.Common\Effects\FlashTarget.puml
!include .\\engine\OpenRA.Mods.Common\Effects\FloatingText.puml
!include .\\engine\OpenRA.Mods.Common\Effects\MapNotificationEffect.puml
!include .\\engine\OpenRA.Mods.Common\Effects\RallyPointIndicator.puml
!include .\\engine\OpenRA.Mods.Common\Effects\RevealShroudEffect.puml
!include .\\engine\OpenRA.Mods.Common\Effects\SpawnActorEffect.puml
!include .\\engine\OpenRA.Mods.Common\Effects\SpriteAnnotation.puml
!include .\\engine\OpenRA.Mods.Common\Effects\SpriteEffect.puml
!include .\\engine\OpenRA.Mods.Common\FileFormats\Blast.puml
!include .\\engine\OpenRA.Mods.Common\FileFormats\FastByteReader.puml
!include .\\engine\OpenRA.Mods.Common\FileFormats\ImaAdpcmReader.puml
!include .\\engine\OpenRA.Mods.Common\FileFormats\IniFile.puml
!include .\\engine\OpenRA.Mods.Common\FileFormats\InstallShieldCABCompression.puml
!include .\\engine\OpenRA.Mods.Common\FileFormats\MSCabCompression.puml
!include .\\engine\OpenRA.Mods.Common\FileFormats\RLEZerosCompression.puml
!include .\\engine\OpenRA.Mods.Common\FileFormats\VqaReader.puml
!include .\\engine\OpenRA.Mods.Common\FileFormats\WavReader.puml
!include .\\engine\OpenRA.Mods.Common\FileSystem\InstallShieldPackage.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\ActorPreview.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\BeamRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\CircleAnnotationRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\ContrailRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\DefaultSpriteSequence.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\DetectionCircleAnnotationRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\IsometricSelectionBarsAnnotationRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\IsometricSelectionBoxAnnotationRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\LineAnnotationRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\ModelActorPreview.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\ModelRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\PolygonAnnotationRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\RailgunRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\RangeCircleAnnotationRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\SelectionBarsAnnotationRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\SelectionBoxAnnotationRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\SpriteActorPreview.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\TextAnnotationRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\TilesetSpecificSpriteSequence.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\UIModelRenderable.puml
!include .\\engine\OpenRA.Mods.Common\Graphics\UITextRenderable.puml
!include .\\engine\OpenRA.Mods.Common\HitShapes\Capsule.puml
!include .\\engine\OpenRA.Mods.Common\HitShapes\Circle.puml
!include .\\engine\OpenRA.Mods.Common\HitShapes\IHitShape.puml
!include .\\engine\OpenRA.Mods.Common\HitShapes\Polygon.puml
!include .\\engine\OpenRA.Mods.Common\HitShapes\Rectangle.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckActorReferences.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckActors.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckAngle.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckChromeHotkeys.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckChromeLogic.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckConditions.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckConflictingMouseBounds.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckDefaultVisibility.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckHitShapes.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckLocomotorReferences.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckMapCordon.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckMapMetadata.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckNotifications.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckPalettes.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckPlayers.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckRangeLimit.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckRevealFootprint.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckSequences.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckSpriteBodies.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckSyncAnnotations.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckTooltips.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckTraitPrerequisites.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckUnknownTraitFields.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckUnknownWeaponFields.puml
!include .\\engine\OpenRA.Mods.Common\Lint\CheckVoiceReferences.puml
!include .\\engine\OpenRA.Mods.Common\Lint\LintBuildablePrerequisites.puml
!include .\\engine\OpenRA.Mods.Common\Lint\LintExts.puml
!include .\\engine\OpenRA.Mods.Common\LoadScreens\BlankLoadScreen.puml
!include .\\engine\OpenRA.Mods.Common\LoadScreens\LogoStripeLoadScreen.puml
!include .\\engine\OpenRA.Mods.Common\LoadScreens\ModContentLoadScreen.puml
!include .\\engine\OpenRA.Mods.Common\LoadScreens\SheetLoadScreen.puml
!include .\\engine\OpenRA.Mods.Common\Orders\BeaconOrderGenerator.puml
!include .\\engine\OpenRA.Mods.Common\Orders\DeployOrderTargeter.puml
!include .\\engine\OpenRA.Mods.Common\Orders\EnterAlliedActorTargeter.puml
!include .\\engine\OpenRA.Mods.Common\Orders\ForceModifiersOrderGenerator.puml
!include .\\engine\OpenRA.Mods.Common\Orders\GlobalButtonOrderGenerator.puml
!include .\\engine\OpenRA.Mods.Common\Orders\GuardOrderGenerator.puml
!include .\\engine\OpenRA.Mods.Common\Orders\OrderGenerator.puml
!include .\\engine\OpenRA.Mods.Common\Orders\PlaceBuildingOrderGenerator.puml
!include .\\engine\OpenRA.Mods.Common\Orders\RepairOrderGenerator.puml
!include .\\engine\OpenRA.Mods.Common\Orders\UnitOrderTargeter.puml
!include .\\engine\OpenRA.Mods.Common\Pathfinder\BasePathSearch.puml
!include .\\engine\OpenRA.Mods.Common\Pathfinder\CellInfo.puml
!include .\\engine\OpenRA.Mods.Common\Pathfinder\CellInfoLayerPool.puml
!include .\\engine\OpenRA.Mods.Common\Pathfinder\PathCacheStorage.puml
!include .\\engine\OpenRA.Mods.Common\Pathfinder\PathFinderUnitPathCacheDecorator.puml
!include .\\engine\OpenRA.Mods.Common\Pathfinder\PathGraph.puml
!include .\\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.puml
!include .\\engine\OpenRA.Mods.Common\Projectiles\AreaBeam.puml
!include .\\engine\OpenRA.Mods.Common\Projectiles\Bullet.puml
!include .\\engine\OpenRA.Mods.Common\Projectiles\GravityBomb.puml
!include .\\engine\OpenRA.Mods.Common\Projectiles\InstantHit.puml
!include .\\engine\OpenRA.Mods.Common\Projectiles\LaserZap.puml
!include .\\engine\OpenRA.Mods.Common\Projectiles\Missile.puml
!include .\\engine\OpenRA.Mods.Common\Projectiles\NukeLaunch.puml
!include .\\engine\OpenRA.Mods.Common\Projectiles\Railgun.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\CallLuaFunc.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\LuaScript.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Media.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\ScriptTriggers.puml
!include .\\engine\OpenRA.Mods.Common\ServerTraits\LobbyCommands.puml
!include .\\engine\OpenRA.Mods.Common\ServerTraits\LobbySettingsNotification.puml
!include .\\engine\OpenRA.Mods.Common\ServerTraits\MasterServerPinger.puml
!include .\\engine\OpenRA.Mods.Common\ServerTraits\PlayerPinger.puml
!include .\\engine\OpenRA.Mods.Common\SpriteLoaders\PngSheetLoader.puml
!include .\\engine\OpenRA.Mods.Common\SpriteLoaders\ShpTSLoader.puml
!include .\\engine\OpenRA.Mods.Common\Traits\AcceptsDeliveredCash.puml
!include .\\engine\OpenRA.Mods.Common\Traits\AcceptsDeliveredExperience.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ActorSpawner.puml
!include .\\engine\OpenRA.Mods.Common\Traits\AffectsShroud.puml
!include .\\engine\OpenRA.Mods.Common\Traits\AmmoPool.puml
!include .\\engine\OpenRA.Mods.Common\Traits\AppearsOnMapPreview.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Armament.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Armor.puml
!include .\\engine\OpenRA.Mods.Common\Traits\AttackMove.puml
!include .\\engine\OpenRA.Mods.Common\Traits\AttackWander.puml
!include .\\engine\OpenRA.Mods.Common\Traits\AutoCarryable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\AutoCarryall.puml
!include .\\engine\OpenRA.Mods.Common\Traits\AutoTarget.puml
!include .\\engine\OpenRA.Mods.Common\Traits\AutoTargetPriority.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BlocksProjectiles.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BodyOrientation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Capturable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\CapturableProgressBar.puml
!include .\\engine\OpenRA.Mods.Common\Traits\CapturableProgressBlink.puml
!include .\\engine\OpenRA.Mods.Common\Traits\CaptureManager.puml
!include .\\engine\OpenRA.Mods.Common\Traits\CaptureProgressBar.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Captures.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Cargo.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Carryable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\CarryableHarvester.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Carryall.puml
!include .\\engine\OpenRA.Mods.Common\Traits\CashTrickler.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ChangesHealth.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ChangesTerrain.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Cloak.puml
!include .\\engine\OpenRA.Mods.Common\Traits\CombatDebugOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\CommandBarBlacklist.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Contrail.puml
!include .\\engine\OpenRA.Mods.Common\Traits\CreatesShroud.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crushable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\CustomSellValue.puml
!include .\\engine\OpenRA.Mods.Common\Traits\DamagedByTerrain.puml
!include .\\engine\OpenRA.Mods.Common\Traits\DeliversCash.puml
!include .\\engine\OpenRA.Mods.Common\Traits\DeliversExperience.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Demolishable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Demolition.puml
!include .\\engine\OpenRA.Mods.Common\Traits\DetectCloaked.puml
!include .\\engine\OpenRA.Mods.Common\Traits\EjectOnDeath.puml
!include .\\engine\OpenRA.Mods.Common\Traits\EngineerRepair.puml
!include .\\engine\OpenRA.Mods.Common\Traits\EngineerRepairable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\EntersTunnels.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ExitsDebugOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ExperienceTrickler.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Explodes.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ExplosionOnDamageTransition.puml
!include .\\engine\OpenRA.Mods.Common\Traits\GainsExperience.puml
!include .\\engine\OpenRA.Mods.Common\Traits\GivesBounty.puml
!include .\\engine\OpenRA.Mods.Common\Traits\GivesCashOnCapture.puml
!include .\\engine\OpenRA.Mods.Common\Traits\GivesExperience.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Guard.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Guardable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Harvester.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Health.puml
!include .\\engine\OpenRA.Mods.Common\Traits\HitShape.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Huntable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Husk.puml
!include .\\engine\OpenRA.Mods.Common\Traits\IgnoresCloak.puml
!include .\\engine\OpenRA.Mods.Common\Traits\IgnoresDisguise.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Immobile.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Interactable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\IsometricSelectable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\JamsMissiles.puml
!include .\\engine\OpenRA.Mods.Common\Traits\KillsSelf.puml
!include .\\engine\OpenRA.Mods.Common\Traits\LintAttributes.puml
!include .\\engine\OpenRA.Mods.Common\Traits\MapEditorData.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Mobile.puml
!include .\\engine\OpenRA.Mods.Common\Traits\MustBeDestroyed.puml
!include .\\engine\OpenRA.Mods.Common\Traits\OwnerLostAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Parachutable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ParaDrop.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Passenger.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Plug.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Pluggable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\PowerTooltip.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ProducibleWithLevel.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Production.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ProductionFromMapEdge.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ProductionParadrop.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ProductionQueueFromSelection.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ProximityCaptor.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ProximityCapturable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\QuantizeFacingsFromSequence.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Rearmable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\RejectsOrders.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ReloadAmmoPool.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Repairable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\RepairableNear.puml
!include .\\engine\OpenRA.Mods.Common\Traits\RepairsBridges.puml
!include .\\engine\OpenRA.Mods.Common\Traits\RepairsUnits.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Replaceable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Replacement.puml
!include .\\engine\OpenRA.Mods.Common\Traits\RequiresSpecificOwners.puml
!include .\\engine\OpenRA.Mods.Common\Traits\RevealOnDeath.puml
!include .\\engine\OpenRA.Mods.Common\Traits\RevealOnFire.puml
!include .\\engine\OpenRA.Mods.Common\Traits\RevealsMap.puml
!include .\\engine\OpenRA.Mods.Common\Traits\RevealsShroud.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ScriptTags.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SeedsResource.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Selectable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Sellable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ShakeOnDeath.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SmokeTrailWhenDamaged.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SpawnActorOnDeath.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SpawnActorsOnSell.puml
!include .\\engine\OpenRA.Mods.Common\Traits\StoresResources.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Targetable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\TemporaryOwnerManager.puml
!include .\\engine\OpenRA.Mods.Common\Traits\TerrainLighting.puml
!include .\\engine\OpenRA.Mods.Common\Traits\TerrainLightSource.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ThrowsParticle.puml
!include .\\engine\OpenRA.Mods.Common\Traits\ThrowsShrapnel.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Tooltip.puml
!include .\\engine\OpenRA.Mods.Common\Traits\TooltipDescription.puml
!include .\\engine\OpenRA.Mods.Common\Traits\TransformCrusherOnCrush.puml
!include .\\engine\OpenRA.Mods.Common\Traits\TransformOnCapture.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Transforms.puml
!include .\\engine\OpenRA.Mods.Common\Traits\TunnelEntrance.puml
!include .\\engine\OpenRA.Mods.Common\Traits\TurnOnIdle.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Turreted.puml
!include .\\engine\OpenRA.Mods.Common\Traits\UpdatesDerrickCount.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Valued.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Voiced.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Wanders.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\UpdatePath.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\UpdateRule.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\UpdateUtils.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\CheckConditionalTraitInterfaceOverrides.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\CheckExplicitInterfacesCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\CheckMissingSprites.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\CheckRuntimeAssembliesCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\CheckYaml.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ConvertSpriteToPngCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\CreateManPage.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\DebugChromeRegions.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\DumpSequenceSheetsCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\Extensions.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ExtractFilesCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ExtractLanguageStringsCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ExtractLuaDocsCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ExtractMapRules.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ExtractSettingsDocsCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ExtractTraitDocsCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ExtractWeaponDocsCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ExtractZeroBraneStudioLuaAPI.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\GetMapHashCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ImportLegacyMapCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\LintInterfaces.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ListInstallShieldCabContentsCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ListInstallShieldContentsCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ListMSCabContentsCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\OutputResolvedRulesCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\OutputResolvedSequencesCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\OutputResolvedWeaponsCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\PngSheetExportMetadataCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\PngSheetImportMetadataCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\RefreshMapCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ReplayMetadataCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\ResizeMapCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\Rgba2Hex.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\UpdateMapCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\UpdateModCommand.puml
!include .\\engine\OpenRA.Mods.Common\UtilityCommands\Utilities.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\ChangeOwnerWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\CreateEffectWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\CreateResourceWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\DamageWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\DestroyResourceWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\FireClusterWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\FlashPaletteEffectWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\GrantExternalConditionWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\HealthPercentageDamageWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\LeaveSmudgeWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\ShakeScreenWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\SpreadDamageWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\TargetDamageWarhead.puml
!include .\\engine\OpenRA.Mods.Common\Warheads\Warhead.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ActorPreviewWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\BackgroundWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\BadgeWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ButtonWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ChatDisplayWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\CheckboxWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ClientTooltipRegionWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ColorBlockWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ColorMixerWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ColorPreviewManagerWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ConfirmationDialogs.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\DropDownButtonWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\EditorViewportControllerWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ExponentialSliderWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\GradientColorBlockWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\GridLayout.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\HotkeyEntryWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\HueSliderWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ImageWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\LabelWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\LabelWithHighlightWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\LabelWithTooltipWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\LineGraphWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ListLayout.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\LogicKeyListenerWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\LogicTickerWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\MapPreviewWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\MenuButtonWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\MouseAttachmentWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ObserverArmyIconsWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ObserverProductionIconsWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ObserverSupportPowerIconsWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\PasswordFieldWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\PerfGraphWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ProductionPaletteWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ProductionTabsWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ProductionTypeButtonWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ProgressBarWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\RadarWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ResourceBarWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\RGBASpriteWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ScrollItemWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ScrollPanelWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\SliderWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\SpriteWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\StrategicProgressWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\SupportPowersWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\SupportPowerTimerWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\TerrainTemplatePreviewWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\TextFieldWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\TooltipContainerWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\ViewportControllerWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\VqaPlayerWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\WidgetUtils.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\WorldButtonWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\WorldInteractionControllerWidget.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\WorldLabelWithTooltipWidget.puml
!include .\\engine\OpenRA.Mods.D2k\Activities\SwallowActor.puml
!include .\\engine\OpenRA.Mods.D2k\Lint\CheckImportActors.puml
!include .\\engine\OpenRA.Mods.D2k\PackageLoaders\D2kSoundResources.puml
!include .\\engine\OpenRA.Mods.D2k\SpriteLoaders\R8Loader.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\AttackSwallow.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\AttractsWorms.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\Sandworm.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\SpiceBloom.puml
!include .\\engine\OpenRA.Mods.D2k\UtilityCommands\D2kMapImporter.puml
!include .\\engine\OpenRA.Mods.D2k\UtilityCommands\ImportD2kMapCommand.puml
!include .\\engine\OpenRA.Mods.D2k\Warheads\DamagesConcreteWarhead.puml
!include .\\engine\OpenRA.Test\OpenRA.Game\ActionQueueTest.puml
!include .\\engine\OpenRA.Test\OpenRA.Game\ActorInfoTest.puml
!include .\\engine\OpenRA.Test\OpenRA.Game\CoordinateTest.puml
!include .\\engine\OpenRA.Test\OpenRA.Game\CPosTest.puml
!include .\\engine\OpenRA.Test\OpenRA.Game\MiniYamlTest.puml
!include .\\engine\OpenRA.Test\OpenRA.Game\OrderTest.puml
!include .\\engine\OpenRA.Test\OpenRA.Game\PlatformTest.puml
!include .\\engine\OpenRA.Test\OpenRA.Game\PriorityQueueTest.puml
!include .\\engine\OpenRA.Test\OpenRA.Game\SpatiallyPartitionedTest.puml
!include .\\engine\OpenRA.Test\OpenRA.Game\VariableExpressionTest.puml
!include .\\engine\OpenRA.Test\OpenRA.Mods.Common\ShapeTest.puml
!include .\\OpenRA.Mods.RA2\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\OpenRA.Mods.RA2\obj\Debug\OpenRA.Mods.RA2.AssemblyInfo.puml
!include .\\OpenRA.Mods.RA2\Traits\Conditions\GrantTimedConditionOnDeploy.puml
!include .\\OpenRA.Mods.RA2\Traits\Render\WithCarrierParentPipsDecoration.puml
!include .\\OpenRA.Mods.RA2\Traits\Render\WithExitOverlay.puml
!include .\\OpenRA.Mods.RA2\Traits\Render\WithMindControlArc.puml
!include .\\OpenRA.Mods.RA2\Traits\Render\WithMindControllerPipsDecoration.puml
!include .\\OpenRA.Mods.RA2\Traits\Render\WithMirageSpriteBody.puml
!include .\\OpenRA.Mods.RA2\Traits\Render\WithTurretDeployAnimation.puml
!include .\\OpenRA.Mods.RA2\Traits\Render\WithVoxelHelicopterBody.puml
!include .\\OpenRA.Mods.RA2\Traits\World\TintedCellsLayer.puml
!include .\\engine\OpenRA.Game\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Game\obj\Debug\OpenRA.Game.AssemblyInfo.puml
!include .\\engine\OpenRA.Game\obj\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Game\obj\Release\OpenRA.Game.AssemblyInfo.puml
!include .\\engine\OpenRA.Game\Traits\Player\FrozenActorLayer.puml
!include .\\engine\OpenRA.Game\Traits\Player\PlayerColorPalette.puml
!include .\\engine\OpenRA.Game\Traits\Player\PlayerHighlightPalette.puml
!include .\\engine\OpenRA.Game\Traits\Player\Shroud.puml
!include .\\engine\OpenRA.Game\Traits\World\DebugVisualizations.puml
!include .\\engine\OpenRA.Game\Traits\World\Faction.puml
!include .\\engine\OpenRA.Game\Traits\World\FixedColorPalette.puml
!include .\\engine\OpenRA.Game\Traits\World\ScreenMap.puml
!include .\\engine\OpenRA.Game\Traits\World\ScreenShaker.puml
!include .\\engine\OpenRA.Launcher\obj\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Launcher\obj\Release\OpenRA.Launcher.AssemblyInfo.puml
!include .\\engine\OpenRA.Mods.Cnc\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Mods.Cnc\obj\Debug\OpenRA.Mods.Cnc.AssemblyInfo.puml
!include .\\engine\OpenRA.Mods.Cnc\obj\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Mods.Cnc\obj\Release\OpenRA.Mods.Cnc.AssemblyInfo.puml
!include .\\engine\OpenRA.Mods.Cnc\Scripting\Properties\ChronosphereProperties.puml
!include .\\engine\OpenRA.Mods.Cnc\Scripting\Properties\DisguiseProperties.puml
!include .\\engine\OpenRA.Mods.Cnc\Scripting\Properties\InfiltrateProperties.puml
!include .\\engine\OpenRA.Mods.Cnc\Scripting\Properties\IonCannonProperties.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Attack\AttackLeap.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Attack\AttackPopupTurreted.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Attack\AttackTDGunboatTurreted.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Attack\AttackTesla.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Buildings\ClonesProducedUnits.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Buildings\TiberianSunRefinery.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Infiltration\InfiltrateForCash.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Infiltration\InfiltrateForDecoration.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Infiltration\InfiltrateForExploration.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Infiltration\InfiltrateForPowerOutage.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Infiltration\InfiltrateForSupportPower.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Infiltration\InfiltrateForSupportPowerReset.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Infiltration\InfiltrateForTransform.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Infiltration\Infiltrates.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\PaletteEffects\ChronoshiftPaletteEffect.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\PaletteEffects\LightPaletteRotator.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithBuildingBib.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithCargo.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithDisguisingInfantryBody.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithDockingOverlay.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithEmbeddedTurretSpriteBody.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithGunboatBody.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithHarvesterSpriteBody.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithLandingCraftAnimation.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithRoof.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithTeslaChargeAnimation.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithTeslaChargeOverlay.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithVoxelUnloadBody.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\Render\WithVoxelWalkerBody.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\SupportPowers\AttackOrderPower.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\SupportPowers\ChronoshiftPower.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\SupportPowers\DropPodsPower.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\SupportPowers\GpsPower.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\SupportPowers\GrantPrerequisiteChargeDrainPower.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\SupportPowers\IonCannonPower.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\World\ShroudPalette.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\World\TSShroudPalette.puml
!include .\\engine\OpenRA.Mods.Cnc\Traits\World\VoxelNormalsPalette.puml
!include .\\engine\OpenRA.Mods.Cnc\Widgets\Logic\PreReleaseWarningPrompt.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Air\FallToEarth.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Air\Fly.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Air\FlyAttack.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Air\FlyFollow.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Air\FlyForward.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Air\FlyIdle.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Air\FlyOffMap.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Air\Land.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Air\ReturnToBase.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Air\TakeOff.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Move\AttackMoveActivity.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Move\Drag.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Move\Follow.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Move\Move.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Move\MoveAdjacentTo.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Move\MoveWithinRange.puml
!include .\\engine\OpenRA.Mods.Common\Activities\Move\VisualMoveIntoTarget.puml
!include .\\engine\OpenRA.Mods.Common\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Mods.Common\obj\Debug\OpenRA.Mods.Common.AssemblyInfo.puml
!include .\\engine\OpenRA.Mods.Common\obj\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Mods.Common\obj\Release\OpenRA.Mods.Common.AssemblyInfo.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\ActorGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\AngleGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\BeaconGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\CameraGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\ColorGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\CoordinateGlobals.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\DateTimeGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\FacingGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\LightingGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\MapGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\MediaGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\PlayerGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\RadarGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\ReinforcementsGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\TriggerGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\UserInterfaceGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Global\UtilsGlobal.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\AircraftProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\AirstrikeProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\AmmoPoolProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\CaptureProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\CloakProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\CombatProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\ConditionProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\DeliveryProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\DemolitionProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\DiplomacyProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\GainsExperienceProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\GeneralProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\GuardProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\HarvesterProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\HealthProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\MissionObjectiveProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\MobileProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\NukeProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\ParadropProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\ParatroopersProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\PlayerConditionProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\PlayerExperienceProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\PlayerProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\PlayerStatsProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\PowerProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\ProductionProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\RepairableBuildingProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\ResourceProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\ScaredCatProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\SellableProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\TransformProperties.puml
!include .\\engine\OpenRA.Mods.Common\Scripting\Properties\TransportProperties.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Air\Aircraft.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Air\AttackAircraft.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Air\AttackBomber.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Air\FallsToEarth.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Attack\AttackBase.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Attack\AttackCharges.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Attack\AttackFollow.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Attack\AttackFrontal.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Attack\AttackGarrisoned.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Attack\AttackOmni.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Attack\AttackTurreted.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\BaseBuilderBotModule.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\BuildingRepairBotModule.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\CaptureManagerBotModule.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\HarvesterBotModule.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\McvManagerBotModule.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\SquadManagerBotModule.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\SupportPowerBotModule.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\UnitBuilderBotModule.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\ActorPreviewPlaceBuildingPreview.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\BaseBuilding.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\BaseProvider.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\Bridge.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\BridgeHut.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\BridgePlaceholder.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\Building.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\BuildingInfluence.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\BuildingUtils.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\Exit.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\FootprintPlaceBuildingPreview.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\FreeActor.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\FreeActorWithDelivery.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\Gate.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\GivesBuildableArea.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\GroundLevelBridge.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\LegacyBridgeHut.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\LineBuild.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\LineBuildNode.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\PlaceBuildingVariants.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\PrimaryBuilding.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\ProductionAirdrop.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\RallyPoint.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\Refinery.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\RepairableBuilding.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\RequiresBuildableArea.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\Reservable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\SequencePlaceBuildingPreview.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\TransformsIntoAircraft.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\TransformsIntoEntersTunnels.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\TransformsIntoMobile.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\TransformsIntoPassenger.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\TransformsIntoRepairable.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Buildings\TransformsIntoTransforms.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\ConditionalTrait.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\ExternalCondition.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantCondition.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnAttack.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnBotOwner.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnCombatantOwner.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnDamageState.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnDeploy.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnFaction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnHealth.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnJumpjetLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnLineBuildDirection.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnMovement.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnPlayerResources.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnPowerState.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnPrerequisite.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnProduction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnSubterraneanLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnTerrain.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionOnTunnelLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantConditionWhileAiming.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantExternalConditionToCrusher.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantExternalConditionToProduced.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\GrantRandomCondition.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\LineBuildSegmentExternalCondition.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\PausableConditionalTrait.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\ProximityExternalCondition.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Conditions\ToggleConditionOnOrder.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\Crate.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\CrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\DuplicateUnitCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\ExplodeCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\GiveCashCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\GiveMcvCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\GiveUnitCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\GrantExternalConditionCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\HealActorsCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\HideMapCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\LevelUpCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\RevealMapCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Crates\SupportPowerCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Infantry\ScaredyCat.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Infantry\TakeCover.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Infantry\TerrainModifiesDamage.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Modifiers\AlwaysVisible.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Modifiers\FrozenUnderFog.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Modifiers\HiddenUnderFog.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Modifiers\HiddenUnderShroud.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Modifiers\WithColoredOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\CashTricklerMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\CreatesShroudMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\DamageMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\DetectCloakedMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\FirepowerMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\GainsExperienceMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\GivesExperienceMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\HandicapDamageMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\HandicapFirepowerMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\HandicapProductionTimeMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\HarvesterResourceMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\InaccuracyMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\PowerMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\ProductionCostMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\ProductionTimeMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\RangeMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\RefineryResourceMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\ReloadAmmoDelayMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\ReloadDelayMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\RevealsShroudMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Multipliers\SpeedMultiplier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\PaletteEffects\CloakPaletteEffect.puml
!include .\\engine\OpenRA.Mods.Common\Traits\PaletteEffects\FlashPaletteEffect.puml
!include .\\engine\OpenRA.Mods.Common\Traits\PaletteEffects\GlobalLightingPaletteEffect.puml
!include .\\engine\OpenRA.Mods.Common\Traits\PaletteEffects\MenuPaletteEffect.puml
!include .\\engine\OpenRA.Mods.Common\Traits\PaletteEffects\RotationPaletteEffect.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\AllyRepair.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\BaseAttackNotifier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\ClassicParallelProductionQueue.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\ClassicProductionQueue.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\ConquestVictoryConditions.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\DeveloperMode.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\DummyBot.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\EnemyWatcher.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\GrantConditionOnPrerequisiteManager.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\HarvesterAttackNotifier.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\MissionObjectives.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\ModularBot.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\ParallelProductionQueue.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\PlaceBeacon.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\PlaceBuilding.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\PlayerExperience.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\PlayerRadarTerrain.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\PlayerResources.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\PlayerStatistics.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\ProductionQueue.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\ProvidesPrerequisite.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\ProvidesTechPrerequisite.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\ResourceStorageWarning.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\StrategicVictoryConditions.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\TechTree.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Player\TimeLimitManager.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Power\AffectedByPowerOutage.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Power\Power.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Power\ScalePowerWithHealth.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Radar\AppearsOnRadar.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Radar\ProvidesRadar.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Radar\RadarColorFromTerrain.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\CashTricklerBar.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\CustomTerrainDebugOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\DrawLineToTarget.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\Hovers.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\IsometricSelectionDecorations.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\LeavesTrails.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\ProductionBar.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\ReloadArmamentsBar.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\RenderDebugState.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\RenderDetectionCircle.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\RenderJammerCircle.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\RenderRangeCircle.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\RenderShroudCircle.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\RenderSprites.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\RenderSpritesEditorOnly.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\RenderUtils.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\RenderVoxels.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\SelectionDecorations.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\SelectionDecorationsBase.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\SupportPowerChargeBar.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\TimedConditionBar.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\VeteranProductionIconOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithAcceptDeliveredCashAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithAimAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithAmmoPipsDecoration.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithAttackAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithAttackOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithBridgeSpriteBody.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithBuildingPlacedAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithBuildingPlacedOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithBuildingRepairDecoration.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithCargoPipsDecoration.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithChargeOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithChargeSpriteBody.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithCrateBody.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithDamageOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithDeadBridgeSpriteBody.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithDeathAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithDecoration.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithDecorationBase.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithDeliveryAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithDockedOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithDockingAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithFacingSpriteBody.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithGateSpriteBody.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithHarvestAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithHarvesterPipsDecoration.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithHarvestOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithIdleAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithIdleOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithInfantryBody.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithMakeAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithMoveAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithMuzzleOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithNameTagDecoration.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithParachute.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithProductionDoorOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithProductionOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithRangeCircle.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithRepairOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithResourceLevelOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithResourceLevelSpriteBody.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithResourceStoragePipsDecoration.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithResupplyAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithShadow.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithSpriteBarrel.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithSpriteBody.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithSpriteControlGroupDecoration.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithSpriteTurret.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithSupportPowerActivationAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithSupportPowerActivationOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithTextControlGroupDecoration.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithTextDecoration.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithTurretAimAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithTurretAttackAnimation.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithVoxelBarrel.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithVoxelBody.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithVoxelTurret.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Render\WithWallSpriteBody.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Sound\ActorLostNotification.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Sound\AmbientSound.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Sound\AnnounceOnKill.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Sound\AnnounceOnSeen.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Sound\AttackSounds.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Sound\CaptureNotification.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Sound\DeathSounds.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Sound\SoundOnDamageTransition.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Sound\VoiceAnnouncement.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SupportPowers\AirstrikePower.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SupportPowers\GrantExternalConditionPower.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SupportPowers\NukePower.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SupportPowers\ParatroopersPower.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SupportPowers\ProduceActorPower.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SupportPowers\SelectDirectionalTarget.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SupportPowers\SpawnActorPower.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SupportPowers\SupportPower.puml
!include .\\engine\OpenRA.Mods.Common\Traits\SupportPowers\SupportPowerManager.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ActorMap.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ActorSpawnManager.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\BridgeLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\CliffBackImpassabilityLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\CrateSpawner.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\CreateMPPlayers.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\DomainIndex.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\EditorActionManager.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\EditorActorLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\EditorActorPreview.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\EditorCursorLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\EditorResourceLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\EditorSelectionLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ElevatedBridgeLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ElevatedBridgePlaceholder.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ExitsDebugOverlayManager.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\GameSaveViewportManager.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\IndexedPalette.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\IndexedPlayerPalette.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\JumpjetActorLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\JumpjetLocomotor.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\LegacyBridgeLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\LoadWidgetAtGameStart.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\LobbyPrerequisiteCheckbox.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\Locomotor.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\MapBuildRadius.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\MapCreeps.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\MapOptions.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\MissionData.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\MPStartLocations.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\MPStartUnits.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\MusicPlaylist.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\PaletteFromEmbeddedSpritePalette.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\PaletteFromFile.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\PaletteFromGimpOrJascFile.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\PaletteFromPaletteWithAlpha.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\PaletteFromPlayerPaletteWithAlpha.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\PaletteFromPng.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\PaletteFromRGBA.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\PathFinder.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\RadarPings.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ResourceClaimLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ResourceLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ResourceRenderer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ResourceType.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ScriptLobbyDropdown.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\Selection.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ShroudRenderer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\SmudgeLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\SpawnMapActors.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\SpawnMPUnits.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\StartGameNotification.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\SubterraneanActorLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\SubterraneanLocomotor.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\TerrainGeometryOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\TerrainRenderer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\TerrainTunnel.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\TerrainTunnelLayer.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\ValidateOrder.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\WarheadDebugOverlay.puml
!include .\\engine\OpenRA.Mods.Common\Traits\World\WeatherOverlay.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\CopyIsometricSelectableHeight.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\RemoveTurnToDock.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\RenameSmudgeSmokeFields.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\AssetBrowserLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\ButtonTooltipLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\ColorPickerLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\ConnectionLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\CreditsLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\DirectConnectLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\DisconnectWatcherLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\GameSaveBrowserLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\IntroductionPromptLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\MainMenuLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\MapChooserLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\MissionBrowserLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\MultiplayerLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\MusicHotkeyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\MusicPlayerLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\MuteHotkeyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\MuteIndicatorLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\PerfDebugLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\PlayerProfileLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\ReplayBrowserLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\ReplayUtils.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\ScreenshotHotkeyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\ServerCreationLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\ServerListLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\SettingsLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\SimpleTooltipLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\SingleHotkeyBaseLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\SystemInfoPromptLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\TabCompletionLogic.puml
!include .\\engine\OpenRA.Mods.D2k\obj\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Mods.D2k\obj\Release\OpenRA.Mods.D2k.AssemblyInfo.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\Buildings\D2kActorPreviewPlaceBuildingPreview.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\Buildings\D2kBuilding.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\Player\HarvesterInsurance.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\Render\WithCrumbleOverlay.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\Render\WithDeliveryOverlay.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\World\BuildableTerrainLayer.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\World\D2kFogPalette.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\World\D2kResourceRenderer.puml
!include .\\engine\OpenRA.Mods.D2k\Traits\World\PaletteFromScaledPalette.puml
!include .\\engine\OpenRA.Platforms.Default\obj\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Platforms.Default\obj\Release\OpenRA.Platforms.Default.AssemblyInfo.puml
!include .\\engine\OpenRA.Server\obj\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Server\obj\Release\OpenRA.Server.AssemblyInfo.puml
!include .\\engine\OpenRA.Test\obj\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Test\obj\Release\OpenRA.Test.AssemblyInfo.puml
!include .\\engine\OpenRA.Utility\obj\Release\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
!include .\\engine\OpenRA.Utility\obj\Release\OpenRA.Utility.AssemblyInfo.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\BotModuleLogic\BaseBuilderQueueManager.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\BotModuleLogic\SupportPowerDecision.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\Squads\AttackOrFleeFuzzy.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\Squads\Squad.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\Squads\StateMachine.puml
!include .\\engine\OpenRA.Mods.Common\Traits\Power\Player\PowerManager.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20191117\ReplaceAttackTypeStrafe.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200202\AddResourceRenderer.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200202\CreateScreenShakeWarhead.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200202\ReformatChromeProvider.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200202\RemoveAirdropActorTypeDefault.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200202\RemoveInitialFacingHardcoding.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200202\RemoveWithPermanentInjury.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200202\RemoveYesNo.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200202\RenameProneTime.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200202\RenameRallyPointPath.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200202\RenameSpins.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\AddPipDecorationTraits.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\ChangeTargetLineDelayToMilliseconds.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\ConvertSupportPowerRangesToFootprint.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\CreateFlashPaletteEffectWarhead.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\ModernizeDecorationTraits.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\MoveClassicFacingFudge.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\RemoveConditionManager.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\RemoveLaysTerrain.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\RemoveMuzzleSplitFacings.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\RenameCircleOutline.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\RenameHealCrateAction.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\RenameInfiltrationNotifications.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\RenameSelfHealing.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\RenameStances.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\RenameWithNukeLaunch.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\ReplaceBurns.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\ReplaceFacingAngles.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\SpawnActorPowerDefaultEffect.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\SplitDamagedByTerrain.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\UpdateMapInits.puml
!include .\\engine\OpenRA.Mods.Common\UpdateRules\Rules\20200503\UpdateTilesetColors.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\ActorEditLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\ActorSelectorLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\CommonSelectorLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\HistoryLogLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\LayerSelectorLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\MapEditorLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\MapEditorTabsLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\NewMapLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\SaveMapLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Editor\TileSelectorLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\AddFactionSuffixLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\ArmyTooltipLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\ClassicProductionLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\CommandBarLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\ControlGroupLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\DebugLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\DebugMenuLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\GameInfoBriefingLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\GameInfoLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\GameInfoObjectivesLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\GameInfoStatsLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\GameSaveLoadingLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\GameTimerLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\IngameCashCounterLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\IngameChatLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\IngameMenuLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\IngamePowerBarLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\IngamePowerCounterLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\IngameRadarDisplayLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\IngameSiloBarLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\LoadIngamePerfLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\LoadIngamePlayerOrObserverUILogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\LoadMapEditorLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\MenuButtonsChromeLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\ObserverShroudSelectorLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\ObserverStatsLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\OrderButtonsChromeLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\ProductionTabsLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\ProductionTooltipLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\ReplayControlBarLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\StanceSelectorLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\SupportPowerBinLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\SupportPowerTooltipLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\WorldTooltipLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Installation\DownloadPackageLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Installation\InstallFromDiscLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Installation\ModContentDiscTooltipLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Installation\ModContentLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Installation\ModContentPromptLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Lobby\KickClientLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Lobby\KickSpectatorsLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Lobby\LatencyTooltipLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Lobby\LobbyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Lobby\LobbyOptionsLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Lobby\LobbyUtils.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Lobby\MapPreviewLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Lobby\SpawnSelectorTooltipLogic.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\Squads\States\AirStates.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\Squads\States\GroundStates.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\Squads\States\NavyStates.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\Squads\States\ProtectionStates.puml
!include .\\engine\OpenRA.Mods.Common\Traits\BotModules\Squads\States\StateBase.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\CycleBasesHotkeyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\CycleHarvestersHotkeyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\CycleProductionActorsHotkeyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\CycleStatusBarsHotkeyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\JumpToLastEventHotkeyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\JumpToSelectedActorsHotkeyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\PauseHotkeyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\RemoveFromControlGroupHotkeyLogic.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\ResetZoomHotkey.puml
!include .\\engine\OpenRA.Mods.Common\Widgets\Logic\Ingame\Hotkeys\TogglePlayerStanceColorHotkeyLogic.puml
@enduml
