@startuml
class GuardProperties {
    + GuardProperties(context:ScriptContext, self:Actor)
    + Guard(targetActor:Actor) : void
}
class "Requires`1"<T> {
}
ScriptActorProperties <|-- GuardProperties
"Requires`1" "<GuardInfo>" <|-- GuardProperties
"Requires`1" "<IMoveInfo>" <|-- GuardProperties
GuardProperties --> "guard" Guard
@enduml
