@startuml
class IsometricSelectionDecorationsInfo {
    + <<override>> Create(init:ActorInitializer) : object
}
class IsometricSelectionDecorations {
    + IsometricSelectionDecorations(self:Actor, info:IsometricSelectionDecorationsInfo)
    GetDecorationPosition(self:Actor, wr:WorldRenderer, pos:string) : int2
    {static} GetDecorationMargin(pos:string, margin:int2) : int2
    Render(self:Actor, wr:WorldRenderer) : IEnumerable<IRenderable>
    ScreenBounds(self:Actor, wr:WorldRenderer) : IEnumerable<Rectangle>
}
class "Requires`1"<T> {
}
SelectionDecorationsBaseInfo <|-- IsometricSelectionDecorationsInfo
"Requires`1" "<IsometricSelectableInfo>" <|-- IsometricSelectionDecorationsInfo
SelectionDecorationsBase <|-- IsometricSelectionDecorations
IRender <|-- IsometricSelectionDecorations
IsometricSelectionDecorations --> "selectable" IsometricSelectable
@enduml
