@startuml
class SupportPowerChargeBarInfo {
    + <<override>> Create(init:ActorInitializer) : object
}
class SupportPowerChargeBar {
    + SupportPowerChargeBar(self:Actor, info:SupportPowerChargeBarInfo)
    GetValue() : float
    GetColor() : Color
    DisplayWhenEmpty : bool <<get>>
    OnOwnerChanged(self:Actor, oldOwner:Player, newOwner:Player) : void
}
class "ConditionalTrait`1"<T> {
}
ConditionalTraitInfo <|-- SupportPowerChargeBarInfo
SupportPowerChargeBarInfo o-> "DisplayRelationships" PlayerRelationship
SupportPowerChargeBarInfo o-> "Color" Color
"ConditionalTrait`1" "<SupportPowerChargeBarInfo>" <|-- SupportPowerChargeBar
ISelectionBar <|-- SupportPowerChargeBar
INotifyOwnerChanged <|-- SupportPowerChargeBar
SupportPowerChargeBar --> "self" Actor
SupportPowerChargeBar --> "spm" SupportPowerManager
@enduml
