@startuml
class WithNameTagDecorationInfo {
    + <<readonly>> MaxLength : int = 10
    + <<readonly>> Font : string = "TinyBold"
    + <<readonly>> UsePlayerColor : bool = false
    + <<override>> Create(init:ActorInitializer) : object
    + <<override>> RulesetLoaded(rules:Ruleset, ai:ActorInfo) : void
}
class WithNameTagDecoration {
    name : string
    + WithNameTagDecoration(self:Actor, info:WithNameTagDecorationInfo)
    OnOwnerChanged(self:Actor, oldOwner:Player, newOwner:Player) : void
}
class "WithDecorationBase`1"<T> {
}
WithDecorationBaseInfo <|-- WithNameTagDecorationInfo
WithNameTagDecorationInfo o-> "Color" Color
"WithDecorationBase`1" "<WithNameTagDecorationInfo>" <|-- WithNameTagDecoration
INotifyOwnerChanged <|-- WithNameTagDecoration
WithNameTagDecoration --> "font" SpriteFont
WithNameTagDecoration --> "color" Color
@enduml
