@startuml
class WithResourceLevelSpriteBodyInfo {
    + <<readonly>> Stages : int = 10
    + <<override>> Create(init:ActorInitializer) : object
    + <<override>> RenderPreviewSprites(init:ActorPreviewInitializer, rs:RenderSpritesInfo, image:string, facings:int, p:PaletteReference) : IEnumerable<IActorPreview>
}
class WithResourceLevelSpriteBody {
    + WithResourceLevelSpriteBody(init:ActorInitializer, info:WithResourceLevelSpriteBodyInfo)
    ConfigureAnimation(self:Actor) : void
    OnOwnerChanged(self:Actor, oldOwner:Player, newOwner:Player) : void
    + <<override>> CancelCustomAnimation(self:Actor) : void
}
WithSpriteBodyInfo <|-- WithResourceLevelSpriteBodyInfo
WithSpriteBody <|-- WithResourceLevelSpriteBody
INotifyOwnerChanged <|-- WithResourceLevelSpriteBody
WithResourceLevelSpriteBody --> "info" WithResourceLevelSpriteBodyInfo
WithResourceLevelSpriteBody --> "playerResources" PlayerResources
@enduml
