@startuml
class RenameHealCrateAction {
    + <<override>> Name : string <<get>>
    + <<override>> Description : string <<get>>
    + <<override>> UpdateActorNode(modData:ModData, actorNode:MiniYamlNode) : IEnumerable<string>
}
UpdateRule <|-- RenameHealCrateAction
@enduml
