@startuml
class ReplaceBurns {
    + <<override>> Name : string <<get>>
    + <<override>> Description : string <<get>>
    + <<override>> UpdateActorNode(modData:ModData, actorNode:MiniYamlNode) : IEnumerable<string>
}
UpdateRule <|-- ReplaceBurns
@enduml
